### ISSUE TITLE
A Flask app holds a reference to itself

### ISSUE THREAD

**Issue by fjarri** [pallets/flask#3761]
```python
from flask import Flask
import objgraph

def make_app():
    app = Flask(__name__)

    @app.route('/')
    def hello_world():
        return 'Hello, World!'

    return app

def test():
    myapp = make_app()
    objgraph.show_backrefs([myapp], filename='backrefs.png', max_depth=6)

test()
```

Here's what the produced reference graph looks like:
![backrefs](https://user-images.githubusercontent.com/30720/93849469-130f0480-fc61-11ea-9985-e74419357ace.png)

Is it the intended behavior? In our library a Flask app is created dynamically in a closure, and as a result it retains anything else that was created in that closure. We work around this by having a trampoline function and passing heavy objects as weakrefs, but it was still unexpected.

### Environment

* Python version: 3.7.5
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
I'm not clear what the problem with this this circular reference is. The static route uses the app to load and send the static file. Since it's specific to the app, and is optional, it's created in the init method, so this is intentional. Nothing about *that* closure would affect a closure you created with a factory function though. It sounds like something else is causing issues with your objects.

If that's not the case, please create a minimal example that demonstrates that the issue you're having is with Flask itself.

**Comment by fjarri** [comment]
A simplified usage pattern is the following:
```
def make_app():
    app = Flask(__name__)

    big_object = BigObject()

    @app.route('/')
    def some_route():
        big_object.use_in_some_way()

    return app

def somewhere():
    myapp = make_app()
    ...
```

`BigObject` opens and holds handles to some files, so when many apps are created in tests, GC simply cannot delete all the reference loops in time, and it overflows the open file limit. If `app` didn't create a circular reference, it would be deleted after its host object, leading to the deletion of `BigObject`, preventing their accumulation. 

But regardless of that, I don't understand why a circular reference here is *necessary.* If you want to keep a back reference to the app in a route, why not use a weakref?

**Comment by davidism** [comment]
> I don't understand why a circular reference here is necessary

Just looked at the code, and it seems pretty clear why it's necessary, it's because the view function for the static route is an instance method, and the static route is added conditionally in `__init__`. The pattern of storing instance methods under another name/structure doesn't seem particularly uncommon in Python, so I'm not sure why Flask needs special handling. Additionally, the only time this comes up is when you're running lots of tests, which doesn't seem to justify adding the complexity of weakrefs when the application is running normally.

It still seems to me that the problem is how you're instantiating/storing your data, not with Flask. First of all, creating the big object in the closure means you have to create it every time `create_app` is called, which seems inefficient for tests as well. Extract it to a view function outside the factory, then register it in the factory.

```python
big = Big()

def process():
    big.use()
    return "done"

def create_app():
    ...
    app.add_url_rule("/process", view_func=process)
    ...
```

**Comment by fjarri** [comment]
> Just looked at the code, and it seems pretty clear why it's necessary, it's because the view function for the static route is an instance method, and the static route is added conditionally in `__init__`.

You can do that without creating a reference cycle, as I illustrated in #3762.

> Additionally, the only time this comes up is when you're running lots of tests, which doesn't seem to justify adding the complexity of weakrefs when the application is running normally.

I guess it's a question of priorities. I do not expect any Python objects to linger until GC collects them. Doesn't matter if it leads to critical bugs only in specific situations - it's simply unexpected. If you create an `OrderedDict`, or a `numpy` array you don't think that you'll need to run `gc.collect()` to get rid of them quickly. The problem I described is just how I discovered it; I would have filed this issue even if it didn't lead to any immediate problems in my applications. Simply because it *can*, and you don't see it coming.

> It still seems to me that the problem is how you're instantiating/storing your data, not with Flask. First of all, creating the big object in the closure means you have to create it every time create_app is called, which seems inefficient for tests as well.

Generally it is more important to run tests in a clean environment. The less objects are reused, the better. Also the solution your propose won't work for another reason: we need several of these apps existing at once (and, naturally, not using the same backend). 

> Second, in production you're probably using mutliple process workers, or distributing over multiple machines, so loading the data for each worker also seems inefficient, and will also cause issues if you're mutating the data. In that case you want to use something like multiprocessing.Manager to safely manage the data separately from the workers.

Production is a different beast. The problems we have are in tests, and I believe making your library easily testable is a part of the good design. (We don't actually load anything on creation; "Big" is figurative. It's a database, and it hogs file descriptors on creation, and there's a limit of 256 per process on many systems, so getting rid of them in time is essential).

> Also, if you need to make sure files are closed, especially during lots of tests, you probably don't want to rely on GC to handle that predictably, regardless of a circular reference. 

CPython's reference counting is predictable enough. It is a de facto standard, and it seems logical to make use of its properties to make objects behave better.

> I don't have a full design off the top of my head, but you'll want some way to get at big and call something like big.close() manually at the end of tests anyway.

It is a workaround, but not a solution. An app can hold references to a lot of things, and if the app persists, so will all those things. Our app is pretty simple, so it's only the database that's causing real problems.

**Comment by davidism** [comment]
Thanks for bringing this up, it's an interesting issue, but I think ultimately it points to a design issue in the app, not Flask. I don't want to keep going back and forth about your app design however, so I'm making the call that in your specific case (baring further redesign), your test cleanup should call `gc.collect()` to ensure resources are collected.

**Comment by jab** [comment]
@davidism and I discussed further and agreed to accept a fix for this, so I just merged #3762 after making some cleanups.

Thank you for the issue report and the PR!

**Comment by davidism** [comment]
This is now breaking other things, when I want to have a `self.json = JSONProvidder(self)` assignment to provide the test still fails. Composition like this is a very common pattern, at it would be meaningless to do it without the `self` in this case, so I'm very likely to remove the test to support that.
